#! /usr/bin/python3

import sys
import requests

username = "admin"
password = "admin"
host = sys.argv[1]
outlet = int(sys.argv[2])
response = requests.get(f"http://{username}:{password}@{host}/cmd.cgi?$A5", timeout=1.0).content.decode('utf-8')
if '$' in response:
    raise Exception("Couldn't fetch outlet state!")
if outlet == 1:
    print("1" if response[1] != '0' else "0")
    sys.exit(0)
if outlet == 2:
    print("1" if response[0] != '0' else "0")
    sys.exit(0)
raise Exception("Unknown outlet!")
